steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/iwasnothing-self-learning/lstmstock', '.' ]
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'push', 'gcr.io/iwasnothing-self-learning/lstmstock' ]
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
    - '-eEuo'
    - 'pipefail'
    - '-c'
    - |-
      ts=`date +%Y%m%d%H%M`
      job_id="mkt_idx_lstm_stock_training_$ts"
      pwd
      key_id=`gcloud beta secrets versions access latest --secret=APCA_API_KEY_ID`
      secret=`gcloud beta secrets versions access latest --secret=APCA_API_SECRET_KEY`
      gcloud ai-platform jobs submit training $job_id \
      --region "us-central1" \
      --master-image-uri=gcr.io/iwasnothing-self-learning/lstmstock:latest \
      --service-account=pubsubsa@iwasnothing-self-learning.iam.gserviceaccount.com \
      --job-dir "gs://iwasnothing-cloudml-job-dir/simple-stock-train" \
      -- --key-id=$key_id --secret=$secret