apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: lstm
spec:
  schedule: "45 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: lstm
            image: 'testing01.azurecr.io/lstm_build:latest'
          restartPolicy: Never